### ISSUE TITLE
pass integration?

### ISSUE THREAD

**Issue by ferdinandyb** [pdobsan/mailctl#4]
I was wondering about the `pass` integration. I though adding `password_store` from the example config would lead to `mailctl` using `pass` to store the token, but it actually didn't. The comment actually does kind of imply this is not going to happen. My question is, is it possible to set `mailctl` up so it store the token with `pass`?

**Comment by pdobsan** [comment]
> I though adding `password_store` from the example config would lead to `mailctl` using `pass` to store the token, but it actually didn't. The comment actually does kind of imply this is not going to happen.

The `password_store` config is for using `pass` for traditional access methods. That has nothing to do with how `mailctl` stores outh credentials.

> My question is, is it possible to set `mailctl` up so it store the token with `pass`?

No, that would not make much sense just complicate things unnecessarily. That is because `pass` is just using `gnupg` for encryption in a similar way how `mailctl` using it itself. Additionally the oauth credentials are transient while a password manger takes care of more static secrets.
Most users also use `pass` with integration of a `git` repo.

**Comment by ferdinandyb** [comment]
Makes sense, thanks!
